# Generated by Django 4.1.5 on 2023-01-16 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyCategorie',
            new_name='Categorie',
        ),
    ]
