# Generated by Django 4.1.5 on 2023-01-30 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_article_author_remove_article_categorie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentaire',
            name='article',
        ),
        migrations.AddField(
            model_name='commentaire',
            name='objet',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commentaire',
            name='prenom',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
